resourcePackages:
  - au.com.infomedix.rest.swagger.resources
prettyPrint: true
cacheTTL: 0
openAPI: 3.0.1
components:
  securitySchemes:
    basicAuth: # <-- arbitrary name for the security scheme
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: JSESSIONID
security:
  - basicAuth: [ ]
  - cookieAuth: [ ]
